SAMPLE_PER_CLASS_DICT = {"NRG": 100, "RG": 50}
ALL_LABEL_CSV = "train_labels.csv"
SAMPLED_LABEL_CSV = "sampled_train_labels_2.csv"
ALL_IMAGE_DIR = "image-data"
SAMPLED_IMAGE_DIR = "sampled-image-data-2"
IMAGE_FILE_EXTENSION = ".jpg"
IMAGE_COLUMN_IDX = 0
LABEL_COLUMN_IDX = 1
CLASS_NAME_ID_MAP = {"NRG": 0, "RG": 1}